return {
  {
    "nvim-treesitter/nvim-treesitter",
    event = "BufRead",
    config = function()
      require("nvim-treesitter.configs").setup({
        autotag = { enable = true },
        highlight = {
          enable = true,
        },
        indent = { enable = true },
        ensure_installed = {
          "astro",
          "bash",
          "c",
          "comment",
          "cpp",
          "css",
          "dart",
          "dockerfile",
          "go",
          "gomod",
          "graphql",
          "html",
          "javascript",
          "jsdoc",
          "json",
          "jsonc",
          "lua",
          "make",
          "markdown",
          "php",
          "prisma",
          "python",
          "regex",
          "rust",
          "ruby",
          "scss",
          "sparql",
          "toml",
          "tsx",
          "typescript",
          "vim",
          "yaml",
        },
      })
    end,
  },
}
