# Change prefix
unbind C-b
set -g prefix C-q

# Options to make tmux more pleasant
set -g mouse on
set -g default-terminal "tmux-256color"
set -g base-index 1
setw -g pane-base-index 1
set-window-option -g mode-keys vi
bind-key -Tcopy-mode-vi y send -X copy-selection

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
# Set basic tmux options
set -g @plugin 'tmux-plugins/tmux-sensible'
# Adds standard pane navigation bindings
set -g @plugin 'tmux-plugins/tmux-pain-control'

# Designed to status bar
set -g @plugin '2kabhishek/tmux2k'
set -g @tmux2k-theme 'catppuccin'
set -g @tmux2k-icons-only true
set -g @tmux2k-pane-active-border-bg 'default'
set -g @tmux2k-pane-border_bg 'default'
set -g @tmux2k-left-plugins "session git cwd"
set -g @tmux2k-right-plugins "cpu ram uptime"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

